project:
  type: website
  output-dir: docs

website:
  title: "DSAN Resources"
  sidebar:
    contents:
      - text: "<i class='bi bi-house pe-1'></i>Home"
        href: index.qmd
format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='/jjcustom.js'></script>"

