project:
  type: website
  output-dir: docs

website:
  title: "DSAN Resources"
  sidebar:
    contents:
      - text: "<i class='bi bi-house pe-1'></i>Home"
        href: index.qmd
format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><script src='/jjcustom.js'></script>"

