project:
  type: website
  output-dir: docs

website:
  title: "DSAN Resources"
  sidebar:
    contents:
      - text: "<i class='bi bi-house pe-1'></i>Home"
        href: index.qmd
      - about.qmd
format:
  html:
    theme: default
    css: styles.css

